version: "3.9"
networks:
  conf-collector:
    driver: bridge
services:
  collector.api:
    container_name: collector.api
    build:
      context: .
      dockerfile: ConfAppCollector.WebApi/Dockerfile
    ports:
      - "80:80" 
    networks:
    - conf-collector
    depends_on:
    - app.db
  app.db:
    container_name:  app.db
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433" 
    networks:
    - conf-collector

volumes:
  postgres-data:
  