version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ConfAppDb
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

volumes:
  postgres-data:
  