version: "3.9"
services:
  ConfAppCollector.WebApi:
    image: ${DOCKER_REGISTRY-}onionarchitectureweb
    container_name: ConfAppCollector.WebApi
    build:
      context: .
      dockerfile: ConfAppCollector.WebApi/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - ConfAppCollector.db

  ConfAppCollector.db:
    container_name: ConfAppCollector.db
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
    - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

